audio_sink = Steam Streaming Speakers
av1_mode = 3
capture = ddx
display_device_prep = ensure_only_display
encoder = nvenc
fps = [60,90,120,144]
hdr_prep = no_operation
hevc_mode = 3
locale = zh
mdns_broadcast = disabled
min_log_level = 6
nvenc_opengl_vulkan_on_dxgi = disabled
nvenc_preset = 4
nvenc_target_quality = 30
nvenc_twopass = disabled
output_name = ZakoHDR
ping_timeout = 20000
port = 34700
qp = 0
resolutions = [1280x720,1920x1080,2560x1080,2560x1440,2560x1600,3440x1440,3840x2160]
system_tray = true
tray_locale = zh
variable_refresh_rate = enabled
vdd_reuse = enabled
wan_encryption_mode = 0
