/**
 * @file tests/unit/test_vdd_edid.cpp
 * @brief Test the Linux virtual display EDID generator.
 *
 * The expected byte vectors were produced by sunshineVD's reference
 * implementation (src/edid/generator.py) with identical inputs.
 */
#include "src/platform/linux/vdd_edid.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <cstdio>
#include <string>

#ifndef _WIN32
namespace {
  std::string
  generate_hex(unsigned int w, unsigned int h, unsigned int fps, bool hdr, const std::string &name) {
    const auto edid = vdd_edid::generate_virtual_display_edid(w, h, fps, hdr, name);
    std::string out;
    for (auto byte : edid) {
      char buf[6];
      std::snprintf(buf, sizeof(buf), "0x%02X,", byte);
      out += buf;
    }
    return out;
  }

  int
  block_checksum(const std::vector<std::uint8_t> &edid, std::size_t start, std::size_t end) {
    int sum = 0;
    for (std::size_t i = start; i < end; ++i) {
      sum += edid[i];
    }
    return sum % 256;
  }
}  // namespace

// 1920x1080@60 with HDR, generated by the reference implementation.
//
// Deviation from sunshineVD's generator.py, applied deliberately: the display
// range-limits descriptor (bytes 95/96) is no longer the hard-coded
// preferred-mode +/-20 window (40-80 Hz), which contradicted 144 Hz modes the
// EDID advertises. It now covers the advertised refresh rates (55-65 Hz for a
// lone 60 Hz mode), matching the Windows driver's "the mode list is the
// authority" behaviour. The base-block checksum is unchanged because the two
// deltas cancel (+15/-15).
constexpr auto REFERENCE_1080P60_HDR_BASE =
  "0x00,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0x00,0x56,0x24,0x44,0x48,0x8C,0x43,0x80,0x07,0x01,0x21,0x01,0x04,0xB5,0x32,0x1C,0xDC,0x1A,0xEE,0x91,0xA3,0x54,0x4C,0x99,0x26,0x0F,0x50,0x54,0x00,0x00,0x00,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0x01,0xC8,0x35,0x80,0x99,0x70,0x38,0x1B,0x40,0x1E,0x3D,0x26,0x00,0xF4,0x18,0x11,0x00,0x00,0x18,0x00,0x00,0x00,0xFC,0x00,0x46,0x6F,0x75,0x6E,0x64,0x61,0x74,0x69,0x6F,0x6E,0x20,0x56,0x44,0x00,0x00,0x00,0xFD,0x00,0x37,0x41,0x1E,0xA0,0xDC,0x00,0x0A,0x20,0x20,0x20,0x20,0x20,0x20,0x00,0x00,0x00,0x10,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0xC0,0x02,0x03,0x1A,0x70,0xE3,0x05,0xE0,0x00,0xE6,0x06,0x07,0x01,0x78,0x5A,0x32,0xE2,0x00,0x00,0x67,0xD8,0x5D,0xC4,0x01,0x78,0x00,0x0";

constexpr auto REFERENCE_1080P60_HDR_CEA =
  "0,0xC8,0x35,0x80,0x99,0x70,0x38,0x1B,0x40,0x1E,0x3D,0x26,0x00,0xF4,0x18,0x11,0x00,0x00,0x18,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x27,";

TEST(VddEdid, MatchesReference1080p60Hdr) {
  const auto edid = vdd_edid::generate_virtual_display_edid(1920, 1080, 60, true, "Foundation VDD");

  ASSERT_EQ(edid.size(), 256u);
  EXPECT_EQ(generate_hex(1920, 1080, 60, true, "Foundation VDD"), std::string(REFERENCE_1080P60_HDR_BASE) + REFERENCE_1080P60_HDR_CEA);
}

TEST(VddEdid, ChecksumsAreValidForCommonModes) {
  const unsigned int modes[][3] = {
    { 1920, 1080, 60 },
    { 1920, 1080, 120 },
    { 2560, 1440, 120 },
    { 2560, 1440, 165 },
    { 3840, 2160, 60 },
    { 1280, 720, 90 },
  };

  for (const auto &mode : modes) {
    for (bool hdr : { false, true }) {
      const auto edid = vdd_edid::generate_virtual_display_edid(mode[0], mode[1], mode[2], hdr, "Foundation VDD");
      EXPECT_EQ(block_checksum(edid, 0, 128), 0) << mode[0] << 'x' << mode[1] << '@' << mode[2] << " base block";
      EXPECT_EQ(block_checksum(edid, 128, 256), 0) << mode[0] << 'x' << mode[1] << '@' << mode[2] << " cea block";
    }
  }
}

TEST(VddEdid, PreferredTimingMatchesRequestedMode) {
  const auto edid = vdd_edid::generate_virtual_display_edid(2560, 1440, 120, false, "Foundation VDD");

  const auto pixel_clock = static_cast<std::uint16_t>(edid[54] | (edid[55] << 8));
  const unsigned int h_active = edid[56] | ((edid[58] >> 4) << 8);
  const unsigned int h_blank = edid[57] | ((edid[58] & 0x0F) << 8);
  const unsigned int v_active = edid[59] | ((edid[61] >> 4) << 8);

  EXPECT_EQ(h_active, 2560u);
  EXPECT_EQ(v_active, 1440u);

  const unsigned int h_total = h_active + h_blank;
  // The generator clamps v_blank in a second pass from the first-pass clock.
  const unsigned int v_blank = std::max(23u, static_cast<unsigned int>(1440 * 0.025));
  const auto expected_clock = static_cast<std::uint16_t>(static_cast<unsigned int>(h_total * (1440 + v_blank) * 120) / 10000);
  EXPECT_EQ(pixel_clock, expected_clock);
}

TEST(VddEdid, HdrBlockPresenceFollowsFlag) {
  const auto with_hdr = vdd_edid::generate_virtual_display_edid(1920, 1080, 60, true, "VDD");
  const auto without_hdr = vdd_edid::generate_virtual_display_edid(1920, 1080, 60, false, "VDD");

  // HDR Static Metadata Data Block (0xE6, 0x06) right after colorimetry
  EXPECT_EQ(with_hdr[136], 0xE6);
  EXPECT_EQ(with_hdr[137], 0x06);
  // Without HDR the first data block is the Video Capability DB (0xE2, 0x00)
  EXPECT_EQ(without_hdr[132], 0xE2);
  EXPECT_EQ(without_hdr[133], 0x00);
}

#endif  // !_WIN32

#ifndef _WIN32
TEST(VddEdid, PersonalizedHdrLuminanceFollowsCtaEncoding) {
  vdd_edid::edid_options opts;
  opts.width_mm = 700;
  opts.height_mm = 400;
  opts.hdr_max_nits = 1200;
  opts.hdr_max_full_nits = 601;
  opts.hdr_min_nits = 1;
  const auto edid = vdd_edid::generate_virtual_display_edid(1920, 1080, 60, opts);

  // CTA-861-H: max/full = nits*100/1499, min = 255*sqrt(nits/1499)
  EXPECT_EQ(edid[140], 0x50);  // 1200 nits -> 80
  EXPECT_EQ(edid[141], 0x28);  // 601 nits -> 40
  EXPECT_EQ(edid[142], 0x06);  // 1 nit -> round(255*sqrt(1/1499)) = 6
}

TEST(VddEdid, ExtraModesFillDtdSlotsWithValidChecksums) {
  vdd_edid::edid_options opts;
  opts.extra_modes = {
    { 1920, 1080, 60 },
    { 1280, 720, 60 },
  };
  const auto edid = vdd_edid::generate_virtual_display_edid(2560, 1440, 120, opts);

  int sum = 0;
  for (std::size_t i = 0; i < 128; ++i) sum += edid[i];
  EXPECT_EQ(sum % 256, 0);

  // Base block dummy slot now carries the 1920x1080@60 DTD
  const auto pixel_clock = static_cast<int>(edid[108] | (edid[109] << 8));
  const unsigned int h_active = edid[110] | ((edid[112] >> 4) << 8);
  EXPECT_EQ(h_active, 1920u);
  EXPECT_GT(pixel_clock, 0);
}

TEST(VddEdid, PhysicalSizeOverrideLandsInDescriptors) {
  vdd_edid::edid_options opts;
  opts.width_mm = 700;
  opts.height_mm = 400;
  vdd_edid::edid_options size_opts;
  size_opts.width_mm = 700;
  size_opts.height_mm = 400;
  const auto edid = vdd_edid::generate_virtual_display_edid(1920, 1080, 60, size_opts);

  EXPECT_EQ(edid[21], 70);   // width cm
  EXPECT_EQ(edid[22], 40);   // height cm
  EXPECT_EQ(edid[66], 188);  // 700 mm low byte (0x2BC)
  EXPECT_EQ(edid[67], 144);  // 400 mm low byte (0x190)
  EXPECT_EQ(edid[68], 0x21); // (700>>8)<<4 | (400>>8) = 0x21
}
#endif
